; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = mcu
include_dir = mcu
default_envs = m5stick-plus2, m5stick-plus, m5stick-s3

[env]
platform = https://github.com/pioarduino/platform-espressif32.git
framework = arduino
monitor_speed = 115200
lib_deps = 
	m5stack/M5Unified
	https://github.com/cujomalainey/ant-arduino.git
	https://github.com/cujomalainey/antplus-arduino.git
	h2zero/NimBLE-Arduino

build_src_filter = +<./> +<tx/> +<bike/>

[env:m5stick-plus]
board = esp32dev
build_flags = 
	-DARDUINO_M5Stick_C_Plus
upload_port = /dev/tty.usbserial-8D52C06A8B
upload_speed = 115200
upload_flags = 
	--no-stub

[env:m5stick-plus2]
board = esp32dev
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags = 
	-DARDUINO_M5Stick_C_Plus2
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

[env:m5stick-s3]
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv
build_flags = 
	-DARDUINO_M5Stick_S3
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
